---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: convertcurrency
  labels:
    app: convertcurrency
    version: v1
  name: convertcurrency
spec:
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 #specifies the max num of pods that can be created over the desired number of pods
      maxUnavailable: 25% #specifies the max num of pods that can be unavailable during the update process
  replicas: 1
  selector:
    matchLabels:
      app: convertcurrency
      version: v1
  template:
    metadata:
      labels:
        app: convertcurrency
        version: v1
    spec:
      containers:
        - 
          name: convertcurrency
          image: arcbadam/convertcurrencyarc1k8:latest
          imagePullPolicy: Always