---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: convertcurrency
    version: v1
  name: convertcurrency
spec:
  ports:
    -
      name: http
      port: 8102
      targetPort: 8102
  
  selector: 
    app: convertcurrency
    version: v1
  type: NodePort